apiVersion: v2
appVersion: main
dependencies:
- alias: addons
  condition: addons.enabled
  name: cluster-addons
  repository: file://./charts/cluster-addons
  version: '0.1.2'
description: Helm chart for deploying a cluster on an OpenStack cloud using Cluster
  API.
name: openstack-cluster
type: application
version: 0.1.2
